### ISSUE TITLE
Windows catches keypresses making some key combinations impossible

### ISSUE THREAD

**Issue by puttesnutte** [digarok/gsplus-legacy-archive#59]
In Windows it's impossible to enter the Apple IIgs control panel, because the key combination Alt-Ctrl-Escape (=Open-Apple-Control-Escape) is used by Windows to switch focus to another window. F1-Ctrl-Escape doesn't work either because Ctrl-Escape opens the Start-menu. Same thing in GSPort and KEGS32.

**Comment by ksherlock** [comment]
[SetWindowsHookEx](https://docs.microsoft.com/en-us/windows/desktop/api/winuser/nf-winuser-setwindowshookexa) WH_KEYBOARD_LL can be used to process keystrokes before Windows acts on them.

The best way to enter the Control panel is:
1. Press down the alt and control keys
2. click your mouse on another window
3. release the alt and control keys
4. go back to to kegs/gsport/gsplus and press escape
5. also press and release the alt and control keys

This depends on a bug where kegs does not realize the keys have been released since it happens out of focus.  So you'll need to press and release them in step 5 so kegs forgets about them.

**Comment by puttesnutte** [comment]
I didn't get it to work your way. However, I discovered that I can enter the Control Panel if I first press Escape and while holding it down press Ctrl-Alt.

**Comment by tolsen64** [comment]
It would be nice if we could map keys to certain things.  Like pressing the Print Screen, Scroll Lock, or Pause/Break keys to enter the control panel.

**Comment by digarok** [comment]
> It would be nice if we could map keys to certain things. Like pressing the Print Screen, Scroll Lock, or Pause/Break keys to enter the control panel.

I totally agree and mentioned that here: https://github.com/digarok/gsplus/issues/66#issuecomment-477165032

I'd like to offer a fully mappable system.  Before I can do that, I need to catch up on these latest fixes for Windows, and a new build system that I've not finished automating.  If you want to open an issue for this, feel free.  Or I will come back to it once I complete the items I mentioned.
